version: '3'

services: 
  app:
    image: ferreirafernandar/echo "# codeeducation_node" >> README.md:latest
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh 
    command: node index
    networks: 
      - app-network 
    tty: true
    depends_on: 
       - db

  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
        - "8000:80"
    networks:
        - app-network
    depends_on:
        - app    
    environment:
        - NGINX_ROOT=/var/www/html/public
        - NGINX_HOST=localhost
        - NGINX_PORT=80

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db 
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes: 
      - ./mysql/data:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - app-network

networks: 
  app-network:
    driver: bridge      